"""tree

Revision ID: 1f1ceb3d4ba2
Revises: d90bda0ce4a4
Create Date: 2022-06-22 11:56:06.911373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1ceb3d4ba2'
down_revision = 'd90bda0ce4a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
