"""trihads

Revision ID: 28edc97fe958
Revises: 602a3988461e
Create Date: 2022-06-22 14:35:02.422150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28edc97fe958'
down_revision = '602a3988461e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
