"""trihads

Revision ID: 3e5752f52d89
Revises: 28edc97fe958
Create Date: 2022-06-22 15:18:54.975666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5752f52d89'
down_revision = '28edc97fe958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
