"""efr

Revision ID: 442632ce1d3e
Revises: fdb30c855835
Create Date: 2022-06-24 15:47:48.235311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442632ce1d3e'
down_revision = 'fdb30c855835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
