"""trihhh

Revision ID: 602a3988461e
Revises: f75d10974be1
Create Date: 2022-06-22 14:32:19.169003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602a3988461e'
down_revision = 'f75d10974be1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pass_added', sa.Column('coords', sa.Integer(), nullable=True))
    op.drop_constraint('pass_added_coord_fkey', 'pass_added', type_='foreignkey')
    op.create_foreign_key(None, 'pass_added', 'coords', ['coords'], ['id'])
    op.drop_column('pass_added', 'coord')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pass_added', sa.Column('coord', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pass_added', type_='foreignkey')
    op.create_foreign_key('pass_added_coord_fkey', 'pass_added', 'coords', ['coord'], ['id'])
    op.drop_column('pass_added', 'coords')
    # ### end Alembic commands ###
