"""tru

Revision ID: d90bda0ce4a4
Revises: dd6942e3d8e5
Create Date: 2022-06-22 10:25:46.021485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90bda0ce4a4'
down_revision = 'dd6942e3d8e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
