"""onn

Revision ID: dd6942e3d8e5
Revises: 32e3ddf3d428
Create Date: 2022-06-22 10:20:58.387495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6942e3d8e5'
down_revision = '32e3ddf3d428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
