"""triii

Revision ID: f75d10974be1
Revises: 1f1ceb3d4ba2
Create Date: 2022-06-22 13:57:34.891538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75d10974be1'
down_revision = '1f1ceb3d4ba2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
